
name: Pipeline CI

on: [push, pull_request]

jobs:
  run_pipeline:
    name: Run pipeline with test data

    # creates a matrix of different os/profile configurations
    strategy:
      matrix:
        os: [ ubuntu-latest ]  # , windows-latest
        profile: [ docker ]
        # exclude:
        #   - os: macos-latest
        #     profile: docker

    runs-on: ${{ matrix.os }}

    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Checkout pipeline
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          update-conda: true
          use-mamba: true
          mamba-version: 0.24.0
          environment-file: environment.yml
          activate-environment: recode_rnaseq
          conda-channels: bioconda, conda-forge

      # - name: Install nextflow with conda/mamba

      #   env:
      #     NXF_VER: "21.10.3"

      #   run: |
      #     conda install mamba -c conda-forge
      #     $CONDA/bin/activate base
      #     mamba env create -f ${GITHUB_WORKSPACE}/environment.yml
      #     $CONDA/bin/activate recode_rnaseq

      - name: Make scripts executable
        run: |
          chmod +x ${GITHUB_WORKSPACE}/bin/*.sh
      
      - name: Run pipeline
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,${{ matrix.profile }} --outdir ./results
