
name: Pipeline CI

on: [push, pull_request]

jobs:
  run_pipeline:
    name: Run pipeline with test data

    # creates a matrix of different os/profile configurations
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ] 
        profile: [ docker, conda ]
        exclude:
          - os: macos-latest
            profile: docker

    runs-on: ${{ matrix.os }}

    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Checkout pipeline
        uses: actions/checkout@v3

      - name: Setup miniconda with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          update-conda: true
          use-mamba: true
          mamba-version: 0.24.0
          environment-file: environment.yml
          activate-environment: recode_rnaseq
          auto-activate-base: false
          conda-channels: bioconda, conda-forge

      - name: Make scripts executable
        run: chmod +x ${GITHUB_WORKSPACE}/bin/*.sh
      
      - name: Run pipeline
        shell: bash -l {0}
        run: nextflow run ${GITHUB_WORKSPACE} -profile test,${{ matrix.profile }} --outdir ./results
