
name: Pipeline CI

on: [push, pull_request]

jobs:
  run_pipeline:
    name: Run pipeline with test data

    # creates a matrix of different os/profile configurations
    strategy:
      matrix:
        os: [ ubuntu-latest ] # , macos-latest
        profile: [ docker, conda ]
        exclude:
          - os: macos-latest
            profile: docker

    runs-on: ${{ matrix.os }}

    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Checkout pipeline
        uses: actions/checkout@v3

      - name: Install nextflow

        env:
          NXF_VER: "21.10.3"

        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

              steps:
      - name: Checkout pipeline
        uses: actions/checkout@v3

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          update-conda: true
          auto-activate-base: false

      - name: Make scripts executable
        run: chmod +x ${GITHUB_WORKSPACE}/bin/*.sh
      
      - name: Run pipeline
        run: nextflow run ${GITHUB_WORKSPACE} -profile test,${{ matrix.profile }} --outdir ./results
