
name: Pipeline CI

on: [push, pull_request]

jobs:
  run_pipeline:
    name: Run pipeline with test data

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        profile: [ docker ]

    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Checkout pipeline
        uses: actions/checkout@v3

      - name: Install nextflow

        env:
          NXF_VER: "21.10.3"

        run: |
          # conda install mamba -c conda-forge
          mamba env create -f ${GITHUB_WORKSPACE}/environment.yml
          conda activate recode_rnaseq

      - name: Make scripts executable
        run: |
          chmod +x ${GITHUB_WORKSPACE}/bin/*.sh
      
      - name: Run pipeline
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test,${{ matrix.profile }} --outdir ./results
